version: '3.7'

services:
  calup-frontend:
    image: rajatchauhan407/calup
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # calup-backend:
  #   image: "rajatchauhan407/calup-server"
  #   build: 
  #     context: ../cal-up-server
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /app/node_modules
  #     - ../cal-up-server:/app